version: '3.9'

services:
  ubuntu-gpu:
    build:
      context: .
      dockerfile: Dockerfile
    image: ubuntu22.04_cuda11.08_image
    container_name: ubuntu22.04_cuda11.08_container
    tty: true
    stdin_open: true
    entrypoint: /bin/bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - /share_ssd/yutak/workspace/MMyolo:/workspace
