version: '3.9'

services:
  ubuntu-gpu:
    build:
      context: .
      dockerfile: Dockerfile
    image: ubuntu22.04-gpu-cuda118
    container_name: ubuntu22.04-gpu-cuda118-container
    tty: true
    stdin_open: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
              
    volumes:
      - ./Ubuntu_22.04_CUDA_11.08:/workspace
